from ai_simple_engine_common.consts.model_spec.families import MUSICGEN_MODEL_FAMILY
from ai_simple_engine_common.consts.model_spec.identifiers import FACEBOOK_MUSICGEN_LARGE_MODEL_IDENTIFIER, FACEBOOK_MUSICGEN_MEDIUM_MODEL_IDENTIFIER, FACEBOOK_MUSICGEN_MELODY_MODEL_IDENTIFIER, FACEBOOK_MUSICGEN_SMALL_MODEL_IDENTIFIER


__all__ = [
    'MUSICGEN_MODEL_FAMILY',
    'FACEBOOK_MUSICGEN_LARGE_MODEL_IDENTIFIER',
    'FACEBOOK_MUSICGEN_MEDIUM_MODEL_IDENTIFIER',
    'FACEBOOK_MUSICGEN_MELODY_MODEL_IDENTIFIER',
    'FACEBOOK_MUSICGEN_SMALL_MODEL_IDENTIFIER'
]